name: dot_bottom_nav_bar
description: This dot package provides you with a navigation bar.
version: 0.0.1
homepage: 'https://github.com/amin-allizadeh/dot_bottom_nav_bar.git'

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
